// Group 26
// Rishi Gupta     (2021A7PS0690P)
// Sparsh Goenka   (2021A7PS2413P)
// Utkarsh Sharma  (2021A7PS0693P)
// Saumya Sharma   (2021A7PS0544P)
// Akshat Bajpai   (2021A7PS0573P)
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#include "buffer.h"
#include "hashmap.h"
#include "lexer.h"
#include "parser.h"
#include "stack.h"
#include "tokens.h"
#include "tree.h"

int main(int argc, char* argv[]) {
    if (argc != 3) {
        printf("Usage: ./stage1exe <input_file> <parse_tree_out_file>\n");
        return 0;
    }
    printf("===========================================================================\n");
    printf("-----------------------Welcome to CoCo Compiler v1.0-----------------------\n");
    printf("---------------------------------Group 26----------------------------------\n");
    printf("===========================================================================\n\n");
    printf("This sophisticated compiler has been meticulously crafted to facilitate the compilation process of programs written in CoCo, ensuring precision, efficiency, and reliability.\n\n");

    printf("Implementation Status:\n");
    printf("a:  FIRST and FOLLOW sets semi-automated (details in documentation)\n");
    printf("b:  Lexical Analyser module has been implemented\n");
    printf("c:  Syntactic Analysis module has been implemented\n");
    printf("d:  All modules compile successfully and run without any segmentation fault\n");
    printf("e:  Modules work with all the test case files (t1 to t6)\n");
    printf("f:  Parse Tree constructed and written to file successfully\n");
    printf("g:  Parsing Error Recovery Implemented\n");

    HASHMAP keyword_table = create_keyword_table();
    HASHMAP symbol_map = create_symbol_map();
    int** grammar_rules = get_grammar_rules(symbol_map);
    int* nullable_nt = calloc(NT_LEN, sizeof(int));
    ParseEntry** parse_table = get_parse_table(grammar_rules, symbol_map, nullable_nt);

    int option;

    do {
        printf("\n\nChoose an option:\n");
        printf("0 : For exit\n");
        printf("1 : For removal of comments\n");
        printf("2 : For printing the token list generated by the lexer\n");
        printf("3 : For parsing to verify the syntactic correctness and printing the parse tree\n");
        printf("4 : For printing the total CPU time\n");

        printf("Enter option: ");
        scanf("%d", &option);

        BUF b = read_file(argv[1]);

        switch (option) {
            case 0:
                printf("Exiting...\n");
                break;
            case 1:
                remove_comments(argv[1]);
                break;
            case 2: {
                int line = 1, n;
                while (current(b) != EOF) {
                    get_next_token(b, keyword_table, &line, &n, 1);
                }
                break;
            }
            case 3: {
                TREENODE parse_tree = parse_input_source_code(b, keyword_table, symbol_map, grammar_rules, parse_table, nullable_nt);
                print_parse_tree(argv[2], parse_tree);
                break;
            }
            case 4: {
                clock_t start_time, end_time;
                double total_CPU_time, total_CPU_time_in_seconds;
                start_time = clock();

                TREENODE parse_tree = parse_input_source_code(b, keyword_table, symbol_map, grammar_rules, parse_table, nullable_nt);

                end_time = clock();
                total_CPU_time = (double)(end_time - start_time);
                total_CPU_time_in_seconds = total_CPU_time / CLOCKS_PER_SEC;
                printf("\nTotal CPU Time: %lf\n", total_CPU_time);
                printf("Total CPU Time in seconds: %lf\n", total_CPU_time_in_seconds);
                print_parse_tree(argv[2], parse_tree);
                break;
            }
            default:
                printf("Invalid option. Please choose again.\n");
                break;
        }
        close_buf(b);
    } while (option != 0);

    delete_hashmap(keyword_table);
    delete_hashmap(symbol_map);
    delete_grammar_table(grammar_rules);
    delete_parse_table(parse_table);

    printf("=============================================================================\n");
    printf("--------------------------Thank you for using CoCo!--------------------------\n");
    printf("=============================================================================\n\n");
    printf("Group 26:\n");
    printf("Rishi Gupta     (2021A7PS0690P)\n");
    printf("Sparsh Goenka   (2021A7PS2413P)\n");
    printf("Utkarsh Sharma  (2021A7PS0693P)\n");
    printf("Saumya Sharma   (2021A7PS0544P)\n");
    printf("Akshat Bajpai   (2021A7PS0573P)\n");

    return 0;
}