#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#include "buffer.h"
#include "hashmap.h"
#include "lexer.h"
#include "parser.h"
#include "stack.h"
#include "tokens.h"
#include "tree.h"

//     TREENODE parseTree = newNode(string_to_symbol("program", symbol_map));
//     int rule_index = 0;
//     for(int i=0;i<currentRule;i++){
//         printf("%d\n", rules_used[i]);
//     }
//     populateNode(parseTree, rules_used, &rule_index, grammar_rules);
//     // printf("TreeDone\n");
//     // printTree(parseTree, 1);

//     close_buf(b);
//     fclose(fd);

// }

int main(int argc, char* argv[]) {
    if (argc != 3) {
        printf("Usage: ./stage1exe <input_file> <parse_tree_out_file>\n");
        return 0;
    }
    printf("=========================================================================\n");
    printf("----------------------Welcome to CoCo Compiler v1.0----------------------\n");
    printf("=========================================================================\n\n");
    printf("Dear User,\n");
    printf("This sophisticated compiler has been meticulously crafted to facilitate the compilation process of programs written in CoCo, ensuring precision, efficiency, and reliability.\n");

    printf("As you engage with our compiler, we encourage adherence to best practices in software development, leveraging the robust capabilities embedded within our framework to unleash the full potential of your programming endeavors.");

    HASHMAP keyword_table = create_keyword_table();
    HASHMAP symbol_map = create_symbol_map();
    int** grammar_rules = get_grammar_rules(symbol_map);
    int* nullable_nt = calloc(NT_LEN, sizeof(int));
    ParseEntry** parse_table = get_parse_table(grammar_rules, symbol_map, nullable_nt);

    int option;

    do {
        printf("\n\nChoose an option:\n");
        printf("0 : For exit\n");
        printf("1 : For removal of comments\n");
        printf("2 : For printing the token list generated by the lexer\n");
        printf("3 : For parsing to verify the syntactic correctness and printing the parse tree\n");
        printf("4 : For printing the total CPU time\n");

        printf("Enter option: ");
        scanf("%d", &option);

        BUF b = read_file(argv[1]);

        switch (option) {
            case 0:
                printf("Exiting...\n");
                break;
            case 1:
                remove_comments(argv[1]);
                break;
            case 2: {
                int line = 1, n;
                while (current(b) != EOF) {
                    get_next_token(b, keyword_table, &line, &n, 1);
                }
                break;
            }
            case 3: {
                parse_input_source_code(b, argv[2], keyword_table, symbol_map, grammar_rules, parse_table, nullable_nt);
                break;
            }
            case 4: {
                clock_t start_time, end_time;
                double total_CPU_time, total_CPU_time_in_seconds;
                start_time = clock();

                parse_input_source_code(b, NULL, keyword_table, symbol_map, grammar_rules, parse_table, nullable_nt);

                end_time = clock();
                total_CPU_time = (double)(end_time - start_time);
                total_CPU_time_in_seconds = total_CPU_time / CLOCKS_PER_SEC;
                printf("\nTotal CPU Time: %lf\n", total_CPU_time);
                printf("Total CPU Time: %lf sec\n", total_CPU_time_in_seconds);
                break;
            }
            default:
                printf("Invalid option. Please choose again.\n");
                break;
        }
        close_buf(b);
    } while (option != 0);

    delete_hashmap(keyword_table);
    delete_hashmap(symbol_map);

    printf("=================================================================================\n");
    printf("----------------------------Thank you for using CoCo!----------------------------\n");
    printf("=================================================================================\n\n");
    printf("Group Memebers:\n");
    printf("Rishi Gupta     (2021A7PS0690P)\n");
    printf("Sparsh Goenka   (2021A7PS2413P)\n");
    printf("Utkarsh Sharma  (2021A7PS0693P)\n");
    printf("Saumya Sharma   (2021A7PS0544P)\n");
    printf("Akshat Bajpai   (2021A7PS0573P)\n");

    return 0;
}